/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import modelos.Entrenador;
import modelos.Persona;

/**
 *
 * @author Laura Trujillo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private String user;
    private String contra;

    public Login() {
        initComponents();
        user = "admin";
        contra = "1234";
        txtcnombre.setEnabled(false);
        txtcsexo.setEnabled(false);
        txtcedad.setEnabled(false);
        txtcregion.setEnabled(false);
        txtcusuario.setEnabled(false);
        txtccontraseña.setEnabled(false);
        btCyI.setEnabled(false);

    }

    public void cargar() {
        String usuario = txtuser.getText();
        String contraseña = txtcontra.getText();
        if (usuario.equals(user) && contraseña.equals(contra)) {
            Persona person = new Persona();
            Entrenador entrena = new Entrenador();
            person.setNombre("Administrador");
            person.setSexo("hombre");
            person.setEdad(18);
            entrena.setUsuario(user);
            entrena.setContraseña(contra);
            entrena.setRegion("Pueblo Paleta");
            JOptionPane.showMessageDialog(null, "Usuario correcto,  Bienvenido "+user);

            Carga mic=new Carga();
            mic.setVisible(true);
            dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña erroneo");
        }
    }

    public void habilitador() {
        txtcnombre.setEnabled(true);
        txtcsexo.setEnabled(true);
        txtcedad.setEnabled(true);
        txtcregion.setEnabled(true);
        txtcusuario.setEnabled(true);
        txtccontraseña.setEnabled(true);
        btCyI.setEnabled(true);
        txtuser.setEnabled(false);
        txtcontra.setEnabled(false);
        btIngresar.setEnabled(false);
    }

    public void crearingresar() {
        if (!txtcnombre.getText().isEmpty() && !txtcsexo.getText().isEmpty() && !txtcedad.getText().isEmpty() && !txtcregion.getText().isEmpty() && !txtcusuario.getText().isEmpty() && !txtccontraseña.getText().isEmpty()) {
            Persona person = new Persona();
            Entrenador entrena = new Entrenador();
            person.setNombre(txtcnombre.getText());
            person.setSexo(txtcsexo.getText());
            person.setEdad(Integer.parseInt(txtcedad.getText()));
            entrena.setUsuario(txtcusuario.getText());
            entrena.setContraseña(txtccontraseña.getText());
            entrena.setRegion(txtcregion.getText());
            JOptionPane.showMessageDialog(null, "Usuario creado correctamente");
            contra = entrena.getContraseña();
            user = entrena.getUsuario();
            txtcnombre.setEnabled(false);
            txtcsexo.setEnabled(false);
            txtcedad.setEnabled(false);
            txtcregion.setEnabled(false);
            txtcusuario.setEnabled(false);
            txtccontraseña.setEnabled(false);
            btCyI.setEnabled(false);
            txtuser.setEnabled(true);
            txtcontra.setEnabled(true);
            btIngresar.setEnabled(true);

        } else {
            JOptionPane.showMessageDialog(null, "No puedes dejar campos vacios");
        }
    }
    
    public void limpiar(){
        txtcnombre.setText("");
        txtcsexo.setText("");
        txtcedad.setText("");
        txtcregion.setText("");
        txtcusuario.setText("");
        txtccontraseña.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcontra = new javax.swing.JTextField();
        btIngresar = new javax.swing.JButton();
        btCrear = new javax.swing.JButton();
        btCyI = new javax.swing.JButton();
        txtccontraseña = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcusuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcregion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcedad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcsexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("USUARIO:");

        jLabel2.setText("CONTRASEÑA:");

        btIngresar.setText("INGRESAR");
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });

        btCrear.setText("CREAR CUENTA");
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });

        btCyI.setText("CREAR");
        btCyI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCyIActionPerformed(evt);
            }
        });

        jLabel8.setText("CONTRASEÑA:");

        jLabel7.setText("USUARIO:");

        jLabel6.setText("REGION:");

        jLabel5.setText("EDAD:");

        jLabel4.setText("SEXO:");

        jLabel3.setText("NOMBRE:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura (1).jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btIngresar)
                        .addGap(39, 39, 39)
                        .addComponent(btCrear))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcnombre)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtcsexo)
                            .addComponent(jLabel5)
                            .addComponent(txtcedad)
                            .addComponent(jLabel6)
                            .addComponent(txtcregion)
                            .addComponent(jLabel7)
                            .addComponent(txtcusuario)
                            .addComponent(jLabel8)
                            .addComponent(txtccontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btCyI, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcregion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtccontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCyI)
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIngresar)
                    .addComponent(btCrear))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed
        cargar();
    }//GEN-LAST:event_btIngresarActionPerformed

    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed
        habilitador();
    }//GEN-LAST:event_btCrearActionPerformed

    private void btCyIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCyIActionPerformed
        crearingresar();
        limpiar();
    }//GEN-LAST:event_btCyIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrear;
    private javax.swing.JButton btCyI;
    private javax.swing.JButton btIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtccontraseña;
    private javax.swing.JTextField txtcedad;
    private javax.swing.JTextField txtcnombre;
    private javax.swing.JTextField txtcontra;
    private javax.swing.JTextField txtcregion;
    private javax.swing.JTextField txtcsexo;
    private javax.swing.JTextField txtcusuario;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
